### PR TITLE
remove libtool files for libgmpxx

### PR DESCRIPTION
**Pull request by stephan-hof**
This is an attempt to fix the issue mentioned here: https://github.com/bincrafters/community/issues/888#issuecomment-520867875

### CODE REVIEW

**Review by SSE4 — APPROVED** [review]

**Comment by stephan-hof** [comment]
Hi. Thanks for approving. Either you or somebody else has to merge it as well.

**Comment by SSE4** [comment]
yes, just waiting for CI to be sure

**Comment by uilianries** [comment]
Seems like GMP is not able to be built by Clang 8

https://travis-ci.com/bincrafters/conan-gmp/jobs/225083543#L672

```
checking for build system compiler math library... -lm
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ accepts -g... yes
checking C++ compiler clang++ -DNDEBUG -m32 -O3 -fPIC -stdlib=libc++... no
configure: error: C++ compiler not available, see config.log for details
```

That's weird because this PR does not affect that stage.

**Comment by SSE4** [comment]
check config.log, it should have some helpful information

**Comment by uilianries** [comment]
The docker image conanio/clang8 doesn't support x86 build with libc++. I'll add a new patch

**Comment by uilianries** [comment]
All fixed!

**Pull request merged**
